# oh-my-zsh defaults ------------------------------------------------------ {{{
ZSH=$HOME/.oh-my-zsh

case "$OSTYPE" in
  darwin*) OS="OSX" ;;
  linux*) OS="LINUX" ;;
esac
# /oh-my-zsh defaults ----------------------------------------------------- }}}

# PATH -------------------------------------------------------------------- {{{
BASE_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RBENV_PATH=$HOME/.rbenv/shims:$HOME/.rbenv/bin
PYENV_PATH=$HOME/.pyenv/shims:$HOME/.pyenv/bin
if [[ "x$OS" == "xOSX" ]]
then
    # LOCAL_PATH --------------------------------------------------- {{{
    LOCAL_PATH=/usr/X11/bin
    LOCAL_PATH=/usr/local/opt/ruby/bin:$LOCAL_PATH
    LOCAL_PATH=/usr/local/share/npm/bin:$LOCAL_PATH
    LOCAL_PATH=/usr/local/var/go/bin:$LOCAL_PATH
    LOCAL_PATH=/usr/texbin:$LOCAL_PATH
    # /LOCAL_PATH -------------------------------------------------- }}}

    export PATH=$PYENV_PATH:$RBENV_PATH:$LOCAL_PATH:$BASE_PATH
else
    # LOCAL_PATH --------------------------------------------------- {{{
    LOCAL_PATH=''
    # /LOCAL_PATH -------------------------------------------------- }}}

    export PATH=$PYENV_PATH:$RBENV_PATH:$LOCAL_PATH:$BASE_PATH
fi
# /PATH ------------------------------------------------------------------- }}}

# Plugins ----------------------------------------------------------------- {{{
base_plugins=(
    bundler
    capistrano
    django
    fabric
    gem
    git
    git-extras
    mercurial
    mix
    node
    npm
    nvm
    pip
    postgres
    python
    rails4
    rake
    rbenv
    redis-cli
    rsync
    ruby
    taskwarrior
    tmux
    vagrant
    virtualenv
    virtualenvwrapper
    vundle
    zsh-syntax-highlighting
)
if [[ "x$OS" == "xOSX" ]]
then
    local_plugins=(osx brew)
    plugins=($local_plugins $base_plugins)
else
    local_plugins=()
    plugins=($local_plugins $base_plugins)
fi
# /Plugins ---------------------------------------------------------------- }}}

source $ZSH/oh-my-zsh.sh

# OS-specific config ------------------------------------------------------ {{{
BASE_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RBENV_PATH=$HOME/.rbenv/shims:$HOME/.rbenv/bin
PYENV_PATH=$HOME/.pyenv/shims:$HOME/.pyenv/bin
if [[ "x$OS" == "xOSX" ]]
then
    export MAIL=~/Mail
    export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
    export SHELL=/usr/local/bin/zsh
    export JAVA_HOME="$(/usr/libexec/java_home)"
    export PAGER=vimpager

    alias update='curl https://raw.github.com/danieljaouen/dotfiles/master/topics/bin/bootstrap.sh | bash'

    unalias run-help
    autoload run-help
    HELPDIR=/usr/local/share/zsh/helpfiles

    # aws --------------------------------------------------------------------- {{{
    export EC2_PRIVATE_KEY="$(/bin/ls "$HOME"/.ec2/pk-*.pem | /usr/bin/head -1)"
    export EC2_CERT="$(/bin/ls "$HOME"/.ec2/cert-*.pem | /usr/bin/head -1)"
    export EC2_HOME="/usr/local/Library/LinkedKegs/ec2-api-tools/jars"
    export AWS_CREDENTIAL_FILE="$HOME/.boto"
    # /aws -------------------------------------------------------------------- }}}
else
    export SHELL=/usr/bin/zsh
    # eval "$(ssh-agent)"
fi
# /OS-specific config ----------------------------------------------------- }}}

# Global Options and Aliases ---------------------------------------------- {{{
unsetopt correct_all
setopt INTERACTIVE_COMMENTS

export EDITOR=vim
export TERM=screen-256color-bce
export PYENV_ROOT=$HOME/.pyenv
export ANSIBLE_PARAMIKO_AGENT_FORWARDING=sudo_user
export ANSIBLE_NOCOWS=1

alias debug_email="python -m smtpd -n -c DebuggingServer localhost:1025"
alias j="z"
alias l='ls -lah'
alias less=$PAGER
alias mtr="sudo mtr -t"
alias mute="vol 0"
alias n="newsbeuter"
alias serve_this="python -m SimpleHTTPServer 8100"
alias t="task"
alias zless=$PAGER
# /Global Options and Aliases --------------------------------------------- }}}

# ag ---------------------------------------------------------------------- {{{
alias agjs="ag -G '.*\.js$'"
alias agpy="ag -G '.*\.py$'"
alias aghtml="ag -G '.*\.html$'"
alias agyml="ag -G '.*\.yml$'"
alias agrb="ag -G '.*\.rb$'"
# /ag --------------------------------------------------------------------- }}}

# ansible ----------------------------------------------------------------- {{{
alias a="ansible"
alias ap="ansible-playbook"
alias api="ansible-playbook -i"
alias apik="ansible-playbook --ask-sudo-pass -i"
alias apvi="ansible-playbook -vvvv -i"
alias apvik="ansible-playbook -vvvv --ask-sudo-pass -i"
alias apio="ansible-playbook -i ~/.ansible.d/inventories/osx"
alias apios="ansible-playbook -i ~/.ansible.d/inventories/osx ~/.ansible.d/site.yml"
# /ansible ---------------------------------------------------------------- }}}

# git --------------------------------------------------------------------- {{{
alias gc='git commit -m'
alias gp='git'
alias gpu='git'
# /git -------------------------------------------------------------------- }}}

# go ---------------------------------------------------------------------- {{{
export GOPATH=/usr/local/var/go
# /go --------------------------------------------------------------------- }}}

# hg ---------------------------------------------------------------------- {{{
alias h="hg"
alias hc="hg commit -m"
alias hm="hg commit -m 'merge.'"
alias hp="hg"
alias hpu="hg"
alias hqci="hg qci"
alias hqf="hg qf"
alias hqgl="hg qgl"
alias hqi="hg qi"
alias hqlog="hg gqlog"
alias hqn="hg qn"
alias hqpo="hg qpo"
alias hqpoa="hg qpoa"
alias hqpua="hg qpua"
alias hqq="hg qq"
alias hqr="hg qr"
alias hqrm="hg qrm"
alias hqst="hg qst"
alias hup="hg up"
# /hg --------------------------------------------------------------------- }}}

# javascript/node.js ------------------------------------------------------ {{{
. ~/.nvm/nvm.sh
# /javascript/node.js ----------------------------------------------------- }}}

# python/django ----------------------------------------------------------- {{{
eval "$(pyenv init - zsh)"
export PYTHONSTARTUP="$HOME/.pythonrc.py"

if [[ "x$OS" == "xOSX" ]]; then
    . /usr/local/bin/virtualenvwrapper.sh
else
    . /usr/local/bin/virtualenvwrapper.sh
fi
export VIRTUAL_ENV_DISABLE_PROMPT=0

alias daspt='django-admin.py startproject --template=https://github.com/twoscoops/django-twoscoops-project/archive/master.zip --extension=py,rst,html'
alias fd="fab dev"
alias pm="python manage.py"
alias pmm='python manage.py migrate'
alias pmr='python manage.py runserver'
alias pmrp='python manage.py runserver_plus'
alias pmrpg='python manage.py runserver_plus --adminmedia=`pwd`/media/admin'
alias pms='python manage.py shell'
alias pmsdb='python manage.py syncdb'
alias pmsi='python manage.py schemamigration --initial'
alias pmsm='python manage.py schemamigration --auto'
alias pmsp='python manage.py shell_plus'
alias pyr='pyenv rehash'
# /python/django ---------------------------------------------------------- }}}

# ruby/rails -------------------------------------------------------------- {{{
eval "$(rbenv init - zsh)"
alias b='bundle'
alias be='bundle exec'
alias bec='bundle exec cucumber'
alias beg='bundle exec rails generate'
alias ber='bundle exec rake'
alias bers='bundle exec rspec'
alias bi='bundle install'
alias bu='bundle update'
alias rn='rails new'
alias rt='rake ctags'
alias rr='rbenv rehash'

function bug {
    bundle gem $1 --bin --test
}
# /ruby/rails ------------------------------------------------------------- }}}

# vagrant ----------------------------------------------------------------- {{{
alias v="vagrant"
alias vp="vagrant provision"
alias vs="vagrant suspend"
alias vup="vagrant up"
alias vupa="vagrant up --provider=aws"
# /vagrant ---------------------------------------------------------------- }}}

# prompt ------------------------------------------------------------------ {{{
function collapse_pwd {
    echo $(pwd | sed -e "s,^$HOME,~,")
}

function prompt_char {
    git branch >/dev/null 2>/dev/null && echo '±' && return
    hg root >/dev/null 2>/dev/null && echo '☿' && return
    echo '○'
}

function battery_charge {
    echo `$BAT_CHARGE` 2>/dev/null
}

function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}

function hg_prompt_info {
    hg prompt --angle-brackets "\
< on %{$fg[red]%}<branch>%{$reset_color%}>\
< at %{$fg[yellow]%}<tags|%{$reset_color%}, %{$fg[yellow]%}>%{$reset_color%}>\
%{$fg[green]%}<status|modified|unknown><update>%{$reset_color%}<
patches: <patches|join( → )|pre_applied(%{$fg[yellow]%})|post_applied(%{$reset_color%})|pre_unapplied(%{$fg_bold[green]%})|post_unapplied(%{$reset_color%})>>" 2>/dev/null
}

PROMPT='
%{$fg[red]%}%n%{$reset_color%} at %{$fg[yellow]%}%m%{$reset_color%} in %{$fg_bold[green]%}$(collapse_pwd)%{$reset_color%}$(git_prompt_info)$(hg_prompt_info)
$(virtualenv_info)$(prompt_char) '

RPROMPT='$(battery_charge)'

ZSH_THEME_GIT_PROMPT_PREFIX=" on %{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}!"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[green]%}?"
ZSH_THEME_GIT_PROMPT_CLEAN=""
# /prompt ----------------------------------------------------------------- }}}

# Local Configuration ----------------------------------------------------- {{{
if [[ -s $HOME/.zshrc.local ]]; then
    source $HOME/.zshrc.local
fi
# /Local Configuration ---------------------------------------------------- }}}
